In [6]:
import numpy as np

In [12]:
arr = np.array([1,2,3,4,5,6])
arr
arr.shape
arr.size
arr[2:]
type(arr)

numpy.ndarray

In [29]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])
matrix[0,1]
matrix[0][1]
matrix.shape
matrix.size
matrix[:, 0:2]

array([4, 5, 6])

In [31]:
np.mean([1,2,3,4])
np.sqrt([1,2,3,4])

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [37]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([3,6,4,5,6,0])
arr3 = arr1 + arr2
arr3

ValueError: operands could not be broadcast together with shapes (6,) (4,) 

In [35]:
arr1 = np.array([1,2,3,4,5,6])
arr1 = arr1*10+5
arr1

array([15, 25, 35, 45, 55, 65])

In [39]:
my_list = [1,2,3]
my_list = my_list*2+5
my_list

TypeError: can only concatenate list (not "int") to list

In [43]:
temperatures = np.array([
    [10,11,4,0,15,17,17],
    [25,26,24,20,23,27,29],
    [-10,-11,-4,0,-15,-17,-17]
])
# mask = temperatures>0
temperatures[temperatures>0]

array([10, 11,  4, 15, 17, 17, 25, 26, 24, 20, 23, 27, 29])

In [52]:
worker_1 = np.array([2000, 1000, 0, 5000, 500, 0, 100000])
worker_2 = np.array([50000, 0, 0, 0, 0, 0, 0])
worker_1[(worker_1>worker_2) | (worker_1>1000)]
~(worker_1>worker_2)

array([ True, False,  True, False, False,  True, False])

In [56]:
worker_1 = np.array([2000, 1000, 0, 5000, 500, 0, 100000])
worker_1.sum()
worker_1.max()
worker_1.min()
worker_1[worker_1>0].min()

500

In [66]:
temperatures = np.array([
    [10,11,4,0,15,17,17],
    [25,26,24,20,23,27,29],
    [-10,-11,-4,0,-15,-17,-17]
])
temperatures.sum(axis=1)
temperatures.max(axis=0)
temperatures[temperatures>0].max()

29

In [68]:
a = np.array([1,10,5,1000])
b = np.array([1,4,5])
np.intersect1d(a,b)

array([1, 5])

In [69]:
np.arange(2,11,0.5)

array([ 2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,
        7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

In [72]:
np.zeros((3,5), dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [73]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [76]:
np.eye(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [81]:
a = np.arange(32).reshape(4,1,8)
a

array([[[ 0,  1,  2,  3,  4,  5,  6,  7]],

       [[ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29, 30, 31]]])

In [82]:
b = np.arange(48).reshape(1,6,8)
b

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47]]])

In [83]:
a+b

array([[[ 0,  2,  4,  6,  8, 10, 12, 14],
        [ 8, 10, 12, 14, 16, 18, 20, 22],
        [16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54]],

       [[ 8, 10, 12, 14, 16, 18, 20, 22],
        [16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62]],

       [[16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62],
        [56, 58, 60, 62, 64, 66, 68, 70]],

       [[24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62],
        [56, 58, 60, 62, 64, 66, 68, 70],
        [64, 66, 68, 70, 72,

In [92]:
a = np.array([
    [99,2],
    [9,7],
    [5,6]
])
a.T
np.sort(a)
np.sort(a, axis=None)
np.sort(a, axis=0)

array([[ 5,  2],
       [ 9,  6],
       [99,  7]])

In [94]:
a = np.array([
    [1,2],
    [3,4]
])
b = np.array([
    [5,6],
    [7,8]
])
np.hstack((a,b))
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [100]:
np.array([
    [5,6, 9,10],
    [7,8, 1,2]
]).reshape(4,-1)

array([[ 5,  6],
       [ 9, 10],
       [ 7,  8],
       [ 1,  2]])